---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
        name: 💄 Ensuring files are prettier
        types: [yaml, json, markdown]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: "v0.9.0"
    hooks:
      - id: shellcheck
        name: ✅ Check Shell files
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-executables-have-shebangs
        stages: [pre-commit, pre-push, manual]
      - id: check-symlinks
  - repo: local
    hooks:
      - id: ruff
        name: ✅ Format using ruff
        types: [python]
        language: system
        entry: uv run ruff format
      - id: ruff
        name: ✅ Lint using ruff
        types: [python]
        language: system
        entry: uv run ruff check
        args: [--fix, --exit-non-zero-on-fix]
      - id: codespell
        name: ✅ Check code for common misspellings
        language: system
        types: [text]
        exclude: |
          (?x)^(
              .lock
          )$
        entry: uv run codespell --ignore-words=.codespell
      - id: mypy
        name: 🆎 Static type checking using mypy
        language: system
        types: [python]
        entry: uv run mypy
        require_serial: true
      - id: pytest
        name: 🧪 Running tests and test coverage with pytest
        language: system
        types: [python]
        entry: uv run pytest
        pass_filenames: false
      - id: yamllint
        name: 🎗  Check YAML files with yamllint
        language: system
        types: [yaml]
        entry: uv run yamllint
